### ISSUE TITLE
geometry / cylinder API设计不合理

### ISSUE THREAD

**Issue by yelloxing** [oi-contrib/VISLite#10]
![截屏2024-01-10 17 34 06](https://github.com/oi-contrib/VISLite/assets/23074691/0d03e23f-f0cb-4b2d-9611-44168dc725bc)

如果我有2个球，需要连起来（比如画化学分子结构），如果可以直接传递起点和终点是不是更合理？

是否考虑优化一下

**Comment by zxl20070701** [comment]
下个版本会考虑进行兼容改造

**Comment by zxl20070701** [comment]
v0.7.0 已经发布并优化了此问题
