### ISSUE TITLE
canvas / 气压表运行好像有问题

### ISSUE THREAD

**Issue by yelloxing** [oi-contrib/VISLite#12]
https://gitee.com/oi-contrib/VISLite/issues/I8W040

![屏幕截图 2024-01-14 180638](https://github.com/oi-contrib/VISLite/assets/23074691/4fd13c81-6bfc-48b5-b3c7-70e23f53d8d8)

**Comment by zxl20070701** [comment]
好的，我们将进行分析，可能需要一些时间，文件确实存在

**Comment by yelloxing** [comment]
😎

**Comment by zxl20070701** [comment]
已修复

**Comment by yelloxing** [comment]
嗯呢，看见了
