### ISSUE TITLE
webgl变形问题

### ISSUE THREAD

**Issue by yelloxing** [oi-contrib/VISLite#13]
[https://oi-contrib.github.io/VISLite/#/api/webgl/import](https://gitee.com/link?target=https%3A%2F%2Foi-contrib.github.io%2FVISLite%2F%23%2Fapi%2Fwebgl%2Fimport)

[https://oi-contrib.github.io/VISLite/#/api/webgl/getWebGLContext](https://gitee.com/link?target=https%3A%2F%2Foi-contrib.github.io%2FVISLite%2F%23%2Fapi%2Fwebgl%2FgetWebGLContext)

![IMG_0033](https://github.com/oi-contrib/VISLite/assets/23074691/e118026a-f612-4f94-9e40-620ac6367802)

**Comment by zxl20070701** [comment]
赞![89822D38AB234E4A2EC1836C3E79B89E](https://github.com/oi-contrib/VISLite/assets/112325193/15545848-d8b7-4476-a6fd-41ffa5596fec)
