### ISSUE TITLE
优化建议

### ISSUE THREAD

**Issue by cldsx** [oi-contrib/VISLite#14]
大佬大佬，能出个painter.drawArrow()方法快速画出箭头吗

**Comment by yelloxing** [comment]
感觉可以搞个 

```
@vislite/canvas
```
来绘制更多业务图形（canvas版本画笔加强），支持安装，安装以后，原来的canvas画笔就可以直接用这些方法

**Comment by yelloxing** [comment]
然后再搞个

```
@vislite/chart
```

来提供常用图表的数值计算和绘制（分计算层和实现层，方便后续在更多平台上可以直接基于计算层扩展）

**Comment by zxl20070701** [comment]
初步考虑维护相关项目进行扩展（不同意见可以留言评论）
