### ISSUE TITLE
@vislite/canvas

### ISSUE THREAD

**Issue by yelloxing** [oi-contrib/VISLite#15]
感觉可以搞个 

```
@vislite/canvas
```
来绘制更多业务图形（canvas版本画笔加强），支持安装，安装以后，原来的canvas画笔就可以直接用这些方法

_Originally posted by @yelloxing in https://github.com/oi-contrib/VISLite/issues/14#issuecomment-2117119061_

**Comment by zxl20070701** [comment]
这个可以进行讨论，确定具体需求（欢迎留言）

**Comment by zxl20070701** [comment]
@vislite/canvas 已经在孵化中，敬请期待（预计7月份出一个版本）

**Comment by zxl20070701** [comment]
https://github.com/oi-contrib/vislite-plugin-canvas

如果希望更多具体API可以去留言：  https://github.com/oi-contrib/vislite-plugin-canvas/issues
