### ISSUE TITLE
@vislite/chart

### ISSUE THREAD

**Issue by yelloxing** [oi-contrib/VISLite#16]
然后再搞个

```
@vislite/chart
```

来提供常用图表的数值计算和绘制（分计算层和实现层，方便后续在更多平台上可以直接基于计算层扩展）

_Originally posted by @yelloxing in https://github.com/oi-contrib/VISLite/issues/14#issuecomment-2117122073_

**Comment by zxl20070701** [comment]
这个可以进行讨论，确定具体需求（欢迎留言）

**Comment by zxl20070701** [comment]
@vislite/chart 已经在孵化中，敬请期待（预计7月份出一个版本）

**Comment by yelloxing** [comment]
期待

**Comment by zxl20070701** [comment]
https://github.com/oi-contrib/vislite-plugin-chart

已经发布初版
