### ISSUE TITLE
SVG默认文字大小有误

### ISSUE THREAD

**Issue by yelloxing** [oi-contrib/VISLite#5]
**问题描述**
[问题描述：尽可能简洁清晰地把问题描述清楚]
svg的font-size默认值好像和canvas的不一致，而且使用的是奇怪的50

**复现步骤**
[复现问题的步骤]
1. 启动 '...'
2. 点击  '....'
3. 查看

[或者可以直接贴源代码]
```html
<div id="mysvg" style="width:300px;height:300px;outline: 1px solid red;"></div>
<script type="module">
    import { SVG } from 'vislite';

    var painter = new SVG(document.getElementById("mysvg"));

    // 绘制文字
    painter.appendBoard('text').fillText("我爱你，中国～", 50, 20)

    // 绘制球
    painter.config({
        "fillStyle": "pink"
    }).appendBoard('circle').fillCircle(150, 150, 100)

</script>
```

**预期结果**
[使用简洁清晰的语言描述你希望生效的预期结果]
![截屏2023-09-05 17 16 41](https://github.com/oi-contrib/VISLite/assets/23074691/1f37f7cb-d3a3-42d7-8785-cf98b8a61926)

**实际结果**
[这里请贴上你的报错截图或文字]

![截屏2023-09-05 17 16 55](https://github.com/oi-contrib/VISLite/assets/23074691/12507e28-6ef5-4953-81c4-f8f7bad41413)

**系统信息:**
 - 发行平台: [如 微信小程序、H5平台、5+ App等]
 - 操作系统 [如 iOS 12.1.2、Android 7.0]
 - 设备信息 [如 iPhone8 Plus]

**补充信息**
[可选]
[根据你的分析，出现这个问题的原因可能在哪里？]

**Comment by zxl20070701** [comment]
v.0.5.0 进行了修复
