### ISSUE TITLE
SCRIPT5022: SecurityError

### ISSUE THREAD

**Issue by yelloxing** [oi-contrib/VISLite#9]
**问题描述**
[问题描述：尽可能简洁清晰地把问题描述清楚]

运行出现错误：

![屏幕截图 2024-01-07 135247](https://github.com/oi-contrib/VISLite/assets/23074691/64d16e12-a79c-47fc-a359-7f659285c8fd)

**复现步骤**
[复现问题的步骤]
1. 启动 

```
npm run dev
```

2. 启动搜狗浏览器

3. 访问  `http://127.0.0.1:20000/test/mercator/`

3. 最后F12选择IE11

[或者可以直接贴源代码]

**预期结果**
[使用简洁清晰的语言描述你希望生效的预期结果]

正常运行

**实际结果**
[这里请贴上你的报错截图或文字]

出现截图错误（如果未出现，切换页面或多刷新几次）

**系统信息:**
 - 发行平台: [如 微信小程序、H5平台、5+ App等] 搜狗浏览器兼容模式 IE11
 - 操作系统 [如 iOS 12.1.2、Android 7.0] windows 11
 - 设备信息 [如 iPhone8 Plus] 华硕ASUS

**补充信息**
[可选]
[根据你的分析，出现这个问题的原因可能在哪里？]

可能webpack5放弃IE浏览器了，因此这个bug是否需要修复，感觉有待考虑

**Comment by zxl20070701** [comment]
这个先挂着，后续再讨论吧，关于针对IE浏览器的测试，目前采用script方式

>（文档和开发环境目前不考虑低版本理论，额外提供了低版本浏览器修复环境，任何人，如果感觉如此设计不妥或者有更好的建议可以在下面留言）

**Comment by yelloxing** [comment]
💖
